enable extra volume and volumeMount configuration in the refinery dep…
honeycombio/helm-charts pull request #147
Opened 2022-06-07 21:42 UTC by mars64

…loyment

## Which problem is this PR solving?

These changes enable users to define additional `volume` and `volumeMount` configurations for the Refinery deployment object. This is important to enable volume-based secrets handling techniques such as the [secrets-store-csi-driver](https://secrets-store-csi-driver.sigs.k8s.io/).

## Short description of the changes

Adds two new helm values: `volumes: [ ]` and `volumeMounts: [ ]`, uses the existing patterns to call the values using `toYaml` and `nindent`.

## How to verify that this has the expected result

From `./charts/refinery`, I am able to confirm that the chart renders properly _without_ the values set:

```
% helm template -f values.yaml .
```

and _with_ the values set:

```
% cat /tmp/volumes.values.yaml  
extraVolumeMounts:
  - name: honeycomb-secrets
    mountPath: "/mnt/secrets-store"
    readOnly: true

extraVolumes:
  - name: honeycomb-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "honeycomb-secrets"

% helm template -f values.yaml -f /tmp/volumes.values.yaml .
```

2022-06-28 12:42 UTC, MikeGoldsmith commented
Hi @mars64 - thanks for the PR and sorry it's taken so long to get back to you. I'll be reviewing shortly to provide feedback.

2022-06-29 12:39 UTC, MikeGoldsmith requested changes
Looks great, thanks @mars64 👍🏻 

I've left a couple of minor suggestions to tidy up the example text. We don't need the example wording to include how the values will be used in deployment.yaml template 😄

2022-06-29 12:39 UTC, MikeGoldsmith commented on charts/refinery/values.yaml
> +# Use this in conjunction with `.Values.extraVolumes` to map additional volumes into the Refinery pods
```suggestion
# Use to map additional volumes into the Refinery pods 
```

2022-06-29 12:39 UTC, MikeGoldsmith commented on charts/refinery/values.yaml
> +# Use this in conjunction with `.Values.extraVolumeMounts` to map additional volumes into the Refinery pods
```suggestion
# Use to map additional volumes into the Refinery pods 
```

2022-06-29 21:20 UTC, mars64 commented
Applied suggestions. Let me know if you need anything else from me here.

2022-07-01 09:45 UTC, MikeGoldsmith approved these changes
Great, thanks @mars64

2022-07-01 09:45 UTC, merged